name: Feature Request
description: Create a feature request
labels: [Feature Request]

body:
  - type: textarea
    attributes:
        label: Describe the feature
        description: A clear and concise description of what the feature is.
    validations:
        required: true
      

  - type: textarea
    attributes:
        label: Link to documentation 
        description:  A clear and concise documentation.
    
  - type: textarea
    attributes:
        label: Screenshots
        description: If applicable, add screenshots to help explain your problem.

  - type: textarea
    attributes:
        label: Additional context
        description: Add any other context here.
